# Generated by Django 2.2.4 on 2020-05-05 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('floor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_NO', models.CharField(max_length=10)),
                ('No_of_Beds', models.IntegerField()),
                ('No_of_Person_Allowed', models.IntegerField()),
                ('Charges_Per_Person', models.IntegerField()),
                ('AC_Availability', models.BooleanField(default=True)),
                ('Electricity', models.BooleanField(default=True)),
                ('UPS', models.BooleanField(default=True)),
                ('Description', models.TextField(blank=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='floor.floor')),
            ],
        ),
    ]
