# Generated by Django 2.2.4 on 2020-05-05 06:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Renter_Details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField()),
                ('Recepit_No', models.CharField(max_length=10)),
                ('Room_Rent', models.BooleanField(default=True)),
                ('Room_Servece', models.BooleanField(default=True)),
                ('Food_Charges', models.BooleanField(default=True)),
                ('Fine_Charges', models.BooleanField(default=True)),
                ('Internet_Charges', models.BooleanField(default=True)),
                ('Convance_Charges', models.BooleanField(default=True)),
                ('Laundary_Charges', models.BooleanField(default=True)),
                ('Other_Charges', models.BooleanField(default=True)),
                ('Paying_Date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('Description', models.TextField(blank=True)),
                ('Renter_Name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Renter_Details.renter')),
            ],
        ),
    ]
