# Generated by Django 2.2.4 on 2020-05-05 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Renter_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Renter_Details.renter'),
        ),
    ]
