# Generated by Django 2.2.4 on 2020-05-05 06:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Room', '0001_initial'),
        ('floor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='renter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Renter_Name', models.CharField(max_length=200)),
                ('Father_Name', models.CharField(max_length=200)),
                ('Renter_CNIC', models.CharField(max_length=200)),
                ('Mobile_No', models.CharField(max_length=12)),
                ('ICOE_No', models.CharField(max_length=12)),
                ('Renter_Image_scan', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('Renter_CNIC_Image_scan', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('Renter_Profession', models.CharField(max_length=200)),
                ('District', models.CharField(max_length=200)),
                ('Tehseel', models.CharField(max_length=200)),
                ('Complete_Address', models.CharField(max_length=500)),
                ('Advance_payment', models.IntegerField(default=0)),
                ('Checkin_Date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('Expected_Checkout_Date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('Floor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='floor.floor')),
                ('Room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Room.room')),
            ],
        ),
    ]
