# Generated by Django 2.2.4 on 2020-05-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='expendature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reciept_No', models.CharField(max_length=10)),
                ('Amount', models.IntegerField()),
                ('Purpose', models.TextField(blank=True)),
            ],
        ),
    ]
