# Generated by Django 2.2.4 on 2020-05-05 06:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Renter_Details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Visitor_Name', models.CharField(max_length=50)),
                ('Visitor_CNIC_NO', models.CharField(max_length=15)),
                ('Take_In_Time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('Take_Out_Time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('Description', models.TextField(blank=True)),
                ('Renter_Name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Renter_Details.renter')),
            ],
        ),
    ]
